<?php

use Illuminate\Database\Seeder;
use App\Materia;
use App\Carrera;
class MateriasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$materias =
    	[       ['nombre' => 'AC001 Calculo Diferencial.' ,'url_plan_estudio' => 'documentos/1/AC001 Calculo Diferencial.pdf'],
    	['nombre' => 'AC002 Calculo Integral.' ,'url_plan_estudio' => 'documentos/1/AC002 Calculo Integral.pdf'],
    	['nombre' => 'AC003 Algebra Lineal.' ,'url_plan_estudio' => 'documentos/1/AC003 Algebra Lineal.pdf'],
    	['nombre' => 'AC004 Calculo Vectorial.' ,'url_plan_estudio' => 'documentos/1/AC004 Calculo Vectorial.pdf'],
    	['nombre' => 'AC005 Ecuaciones Diferenciales.' ,'url_plan_estudio' => 'documentos/1/AC005 Ecuaciones Diferenciales.pdf'],
    	['nombre' => 'AC006 Fundamentos de Investigacion.' ,'url_plan_estudio' => 'documentos/1/AC006 Fundamentos de Investigacion.pdf'],
    	['nombre' => 'AC007 Taller de Etica.' ,'url_plan_estudio' => 'documentos/1/AC007 Taller de Etica.pdf'],
    	['nombre' => 'AC008 Desarrollo Sustentable.' ,'url_plan_estudio' => 'documentos/1/AC008 Desarrollo Sustentable.pdf'],
    	['nombre' => 'AC009 Taller de Investigacion I.' ,'url_plan_estudio' => 'documentos/1/AC009 Taller de Investigacion I.pdf'],
    	['nombre' => 'AC010 Taller de Investigacion II.' ,'url_plan_estudio' => 'documentos/1/AC010 Taller de Investigacion II.pdf'],
    	['nombre' => 'AE004 Balance de Materia y Energia.' ,'url_plan_estudio' => 'documentos/1/AE004 Balance de Materia y Energia.pdf'],
    	['nombre' => 'AE005 Biologia.' ,'url_plan_estudio' => 'documentos/1/AE005 Biologia.pdf'],
    	['nombre' => 'AE007 Bioquimica.' ,'url_plan_estudio' => 'documentos/1/AE007 Bioquimica.pdf'],
    	['nombre' => 'AE027 Fenomeno de Transporte.' ,'url_plan_estudio' => 'documentos/1/AE027 Fenomeno de Transporte.pdf'],
    	['nombre' => 'AE029 Formulacion y Evaluacion de Proyectos.' ,'url_plan_estudio' => 'documentos/1/AE029 Formulacion y Evaluacion de Proyectos.pdf'],
    	['nombre' => 'AE050 Microbiologia.' ,'url_plan_estudio' => 'documentos/1/AE050 Microbiologia.pdf'],
    	['nombre' => 'AE059 Quimica Analitica.' ,'url_plan_estudio' => 'documentos/1/AE059 Quimica Analitica.pdf'],
    	['nombre' => 'AE060 Quimica Inorganica.' ,'url_plan_estudio' => 'documentos/1/AE060 Quimica Inorganica.pdf'],
    	['nombre' => 'AE065 Termodinamica.' ,'url_plan_estudio' => 'documentos/1/AE065 Termodinamica.pdf'],
    	['nombre' => 'AE33 Fundamentos de Quimica Organica.' ,'url_plan_estudio' => 'documentos/1/AE33 Fundamentos de Quimica Organica.pdf'],
    	['nombre' => 'Análisis Instrumental.' ,'url_plan_estudio' => 'documentos/1/Análisis Instrumental.pdf'],
    	['nombre' => 'Componentes de Equipo Industrial.' ,'url_plan_estudio' => 'documentos/1/Componentes de Equipo Industrial.pdf'],
    	['nombre' => 'Contaminación Atmosférica.' ,'url_plan_estudio' => 'documentos/1/Contaminación Atmosférica.pdf'],
    	['nombre' => 'Dibujo Asistido por Computadora.' ,'url_plan_estudio' => 'documentos/1/Dibujo Asistido por Computadora.pdf'],
    	['nombre' => 'Diseño de Experimentos Ambientales.' ,'url_plan_estudio' => 'documentos/1/Diseño de Experimentos Ambientales.pdf'],
    	['nombre' => 'Ecología.' ,'url_plan_estudio' => 'documentos/1/Ecología.pdf'],
    	['nombre' => 'Economía Ambiental.' ,'url_plan_estudio' => 'documentos/1/Economía Ambiental.pdf'],
    	['nombre' => 'Evaluación de Impacto Ambiental.' ,'url_plan_estudio' => 'documentos/1/Evaluación de Impacto Ambiental.pdf'],
    	['nombre' => 'Fisicoquímica I.' ,'url_plan_estudio' => 'documentos/1/Fisicoquímica I.pdf'],
    	['nombre' => 'Fisicoquímica II.' ,'url_plan_estudio' => 'documentos/1/Fisicoquímica II.pdf'],
    	['nombre' => 'Fundamentos de Aguas Residuales.' ,'url_plan_estudio' => 'documentos/1/Fundamentos de Aguas Residuales.pdf'],
    	['nombre' => 'Física.' ,'url_plan_estudio' => 'documentos/1/Física.pdf'],
    	['nombre' => 'Gestion Ambiental I.' ,'url_plan_estudio' => 'documentos/1/Gestion Ambiental I.pdf'],
    	['nombre' => 'Gestión Ambiental II.' ,'url_plan_estudio' => 'documentos/1/Gestión Ambiental II.pdf'],
    	['nombre' => 'Gestión de Residuos.' ,'url_plan_estudio' => 'documentos/1/Gestión de Residuos.pdf'],
    	['nombre' => 'Ingeniería de Costos.' ,'url_plan_estudio' => 'documentos/1/Ingeniería de Costos.pdf'],
    	['nombre' => 'Mecánica de Fluidos.' ,'url_plan_estudio' => 'documentos/1/Mecánica de Fluidos.pdf'],
    	['nombre' => 'Potabilizacion de Agua.' ,'url_plan_estudio' => 'documentos/1/Potabilizacion de Agua.pdf'],
    	['nombre' => 'Probabilidad y Estadística Ambiental.' ,'url_plan_estudio' => 'documentos/1/Probabilidad y Estadística Ambiental.pdf'],
    	['nombre' => 'Remediación de Suelos.' ,'url_plan_estudio' => 'documentos/1/Remediación de Suelos.pdf'],
    	['nombre' => 'Seguridad e Higiene Industrial.' ,'url_plan_estudio' => 'documentos/1/Seguridad e Higiene Industrial.pdf'],
    	['nombre' => 'Sistemas de Información Geográfica.' ,'url_plan_estudio' => 'documentos/1/Sistemas de Información Geográfica.pdf'],
    	['nombre' => 'Toxicología Ambiental.' ,'url_plan_estudio' => 'documentos/1/Toxicología Ambiental.pdf'],
    	['nombre' => 'AC001 Calculo Diferencial.' ,'url_plan_estudio' => 'documentos/2/AC001 Calculo Diferencial.pdf'],
    	['nombre' => 'AC002 Calculo Integral.' ,'url_plan_estudio' => 'documentos/2/AC002 Calculo Integral.pdf'],
    	['nombre' => 'AC003 Algebra Lineal.' ,'url_plan_estudio' => 'documentos/2/AC003 Algebra Lineal.pdf'],
    	['nombre' => 'AC004 Calculo Vectorial.' ,'url_plan_estudio' => 'documentos/2/AC004 Calculo Vectorial.pdf'],
    	['nombre' => 'AC005 Ecuaciones Diferenciales.' ,'url_plan_estudio' => 'documentos/2/AC005 Ecuaciones Diferenciales.pdf'],
    	['nombre' => 'AC006 Fundamentos de Investigacion.' ,'url_plan_estudio' => 'documentos/2/AC006 Fundamentos de Investigacion.pdf'],
    	['nombre' => 'AC007 Taller de Etica.' ,'url_plan_estudio' => 'documentos/2/AC007 Taller de Etica.pdf'],
    	['nombre' => 'AC008 Desarrollo Sustentable.' ,'url_plan_estudio' => 'documentos/2/AC008 Desarrollo Sustentable.pdf'],
    	['nombre' => 'AC009 Taller de Investigacion I.' ,'url_plan_estudio' => 'documentos/2/AC009 Taller de Investigacion I.pdf'],
    	['nombre' => 'AC010 Taller de Investigacion II.' ,'url_plan_estudio' => 'documentos/2/AC010 Taller de Investigacion II.pdf'],
    	['nombre' => 'Administracion y Legislacion Empresas.' ,'url_plan_estudio' => 'documentos/2/Administracion y Legislacion Empresas.pdf'],
    	['nombre' => 'AE004 Balance de Materia y Energia.' ,'url_plan_estudio' => 'documentos/2/AE004 Balance de Materia y Energia.pdf'],
    	['nombre' => 'AE005 Biologia.' ,'url_plan_estudio' => 'documentos/2/AE005 Biologia.pdf'],
    	['nombre' => 'AE007 Bioquimica.' ,'url_plan_estudio' => 'documentos/2/AE007 Bioquimica.pdf'],
    	['nombre' => 'AE012 Dibujo Asistido por Computadora.' ,'url_plan_estudio' => 'documentos/2/AE012 Dibujo Asistido por Computadora.pdf'],
    	['nombre' => 'AE020 Electromagnetismo.' ,'url_plan_estudio' => 'documentos/2/AE020 Electromagnetismo.pdf'],
    	['nombre' => 'AE029 Formulacion y Evaluacion de Proyectos.' ,'url_plan_estudio' => 'documentos/2/AE029 Formulacion y Evaluacion de Proyectos.pdf'],
    	['nombre' => 'AE039 Instrumentacion y Control.' ,'url_plan_estudio' => 'documentos/2/AE039 Instrumentacion y Control.pdf'],
    	['nombre' => 'AE050 Microbiologia.' ,'url_plan_estudio' => 'documentos/2/AE050 Microbiologia.pdf'],
    	['nombre' => 'AE057 Quimica.' ,'url_plan_estudio' => 'documentos/2/AE057 Quimica.pdf'],
    	['nombre' => 'AE065 Termodinamica.' ,'url_plan_estudio' => 'documentos/2/AE065 Termodinamica.pdf'],
    	['nombre' => 'Analisis instrumental.' ,'url_plan_estudio' => 'documentos/2/Analisis instrumental.pdf'],
    	['nombre' => 'Aseguramiento de la Calidad.' ,'url_plan_estudio' => 'documentos/2/Aseguramiento de la Calidad.pdf'],
    	['nombre' => 'Bioquímica del Nitrógeno y Regulación Genética.' ,'url_plan_estudio' => 'documentos/2/Bioquímica del Nitrógeno y Regulación Genética.pdf'],
    	['nombre' => 'Cinética qumica y biológica.' ,'url_plan_estudio' => 'documentos/2/Cinética qumica y biológica.pdf'],
    	['nombre' => 'Comportamiento Organizacional.' ,'url_plan_estudio' => 'documentos/2/Comportamiento Organizacional.pdf'],
    	['nombre' => 'Estadistica.' ,'url_plan_estudio' => 'documentos/2/Estadistica.pdf'],
    	['nombre' => 'Fenomenos de Transporte II.' ,'url_plan_estudio' => 'documentos/2/Fenomenos de Transporte II.pdf'],
    	['nombre' => 'Fenómenos de Transporte I.' ,'url_plan_estudio' => 'documentos/2/Fenómenos de Transporte I.pdf'],
    	['nombre' => 'Fisica.' ,'url_plan_estudio' => 'documentos/2/Fisica.pdf'],
    	['nombre' => 'Fisicoquimica.' ,'url_plan_estudio' => 'documentos/2/Fisicoquimica.pdf'],
    	['nombre' => 'Higiene y Seguridad.' ,'url_plan_estudio' => 'documentos/2/Higiene y Seguridad.pdf'],
    	['nombre' => 'Ingenieria de Biorreactores.' ,'url_plan_estudio' => 'documentos/2/Ingenieria de Biorreactores.pdf'],
    	['nombre' => 'Ingenieria de Procesos.' ,'url_plan_estudio' => 'documentos/2/Ingenieria de Procesos.pdf'],
    	['nombre' => 'Ingenieria de Proyectos.' ,'url_plan_estudio' => 'documentos/2/Ingenieria de Proyectos.pdf'],
    	['nombre' => 'Ingenieria Economica.' ,'url_plan_estudio' => 'documentos/2/Ingenieria Economica.pdf'],
    	['nombre' => 'Ingenieria y Gestion Ambiental.' ,'url_plan_estudio' => 'documentos/2/Ingenieria y Gestion Ambiental.pdf'],
    	['nombre' => 'Operaciones Unitarias I.' ,'url_plan_estudio' => 'documentos/2/Operaciones Unitarias I.pdf'],
    	['nombre' => 'Operaciones Unitarias II.' ,'url_plan_estudio' => 'documentos/2/Operaciones Unitarias II.pdf'],
    	['nombre' => 'Operaciones Unitarias III.' ,'url_plan_estudio' => 'documentos/2/Operaciones Unitarias III.pdf'],
    	['nombre' => 'Programacion y Metodos Numericos.' ,'url_plan_estudio' => 'documentos/2/Programacion y Metodos Numericos.pdf'],
    	['nombre' => 'Quimica Analitica.' ,'url_plan_estudio' => 'documentos/2/Quimica Analitica.pdf'],
    	['nombre' => 'Química Orgánica I.' ,'url_plan_estudio' => 'documentos/2/Química Orgánica I.pdf'],
    	['nombre' => 'Química Orgánica II.' ,'url_plan_estudio' => 'documentos/2/Química Orgánica II.pdf'],
    	['nombre' => 'AE-09 Control I.' ,'url_plan_estudio' => 'documentos/3/AE-09 Control I.pdf'],
    	['nombre' => 'AE-10 Control I.' ,'url_plan_estudio' => 'documentos/3/AE-10 Control I.pdf'],
    	['nombre' => 'AE-13 Dibujo Asistido por Computadora.' ,'url_plan_estudio' => 'documentos/3/AE-13 Dibujo Asistido por Computadora.pdf'],
    	['nombre' => 'AE-20 Electromagnetismo.' ,'url_plan_estudio' => 'documentos/3/AE-20 Electromagnetismo.pdf'],
    	['nombre' => 'AE-21 ElectrÃ³nica AnalÃ³gica.' ,'url_plan_estudio' => 'documentos/3/AE-21 ElectrÃ³nica AnalÃ³gica.pdf'],
    	['nombre' => 'AE-22 Electronica Digital.' ,'url_plan_estudio' => 'documentos/3/AE-22 Electronica Digital.pdf'],
    	['nombre' => 'AE-38 Instrumentacion.' ,'url_plan_estudio' => 'documentos/3/AE-38 Instrumentacion.pdf'],
    	['nombre' => 'AE-42 Mecanica Clasica.' ,'url_plan_estudio' => 'documentos/3/AE-42 Mecanica Clasica.pdf'],
    	['nombre' => 'AE-51 Probabilidad y EstadÃ­stica.' ,'url_plan_estudio' => 'documentos/3/AE-51 Probabilidad y EstadÃ­stica.pdf'],
    	['nombre' => 'AE-58 Quimica.' ,'url_plan_estudio' => 'documentos/3/AE-58 Quimica.pdf'],
    	['nombre' => 'IELEComunicacion Humana.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Comunicacion Humana.pdf'],
    	['nombre' => 'IELECostos y Presupuestos.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Costos y Presupuestos.pdf'],
    	['nombre' => 'IELEDesarrollo Humano.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Desarrollo Humano.pdf'],
    	['nombre' => 'IELEEquipos Mecanicos.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Equipos Mecanicos.pdf'],
    	['nombre' => 'IELEFisica Moderna.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Fisica Moderna.pdf'],
    	['nombre' => 'IELEInstalaciones Electricas.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Instalaciones Electricas.pdf'],
    	['nombre' => 'IELELegislacion en Materia Electrica.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Legislacion en Materia Electrica.pdf'],
    	['nombre' => 'IELEMecanica de Fluidos y Termodinamica.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Mecanica de Fluidos y Termodinamica.pdf'],
    	['nombre' => 'IELEModelado de Sistemas ElÃ©ctricos de Potencia.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Modelado de Sistemas ElÃ©ctricos de Potencia.pdf'],
    	['nombre' => 'IELEMotores de induccion y Maquinas Especiales.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Motores de induccion y Maquinas Especiales.pdf'],
    	['nombre' => 'IELEProgramacion.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Programacion.pdf'],
    	['nombre' => 'IELESistemas de Iluminacion.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Sistemas de Iluminacion.pdf'],
    	['nombre' => 'IELETecnologia Materiales.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Tecnologia Materiales.pdf'],
    	['nombre' => 'IELETeoria Electromagnetica.' ,'url_plan_estudio' => 'documentos/3/FA ELE-2010-209 Teoria Electromagnetica.pdf'],
    	['nombre' => 'ELE Centrales Electricas.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Centrales Electricas.pdf'],
    	['nombre' => 'ELE Circuitos Electricos I.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Circuitos Electricos I.pdf'],
    	['nombre' => 'ELE Circuitos Electricos II.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Circuitos Electricos II.pdf'],
    	['nombre' => 'ELE Control de Maquinas Electricas.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Control de Maquinas Electricas.pdf'],
    	['nombre' => 'ELE Controladores Logicos Programables.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Controladores Logicos Programables.pdf'],
    	['nombre' => 'ELE Electronica Industrial.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Electronica Industrial.pdf'],
    	['nombre' => 'ELE Gestion Empresarial y Liderazgo.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Gestion Empresarial y Liderazgo.pdf'],
    	['nombre' => 'ELE Instalaciones Electricas Industriales.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Instalaciones Electricas Industriales.pdf'],
    	['nombre' => 'ELE Maquinas Sincronicas y CD.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Maquinas Sincronicas y CD.pdf'],
    	['nombre' => 'ELE Mediciones Electricas.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Mediciones Electricas.pdf'],
    	['nombre' => 'ELE Metodos Numericos.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Metodos Numericos.pdf'],
    	['nombre' => 'ELE Pruebas y Mantenimiento.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Pruebas y Mantenimiento.pdf'],
    	['nombre' => 'ELE Transformadores.' ,'url_plan_estudio' => 'documentos/3/FA IELE-2010-209 Transformadores.pdf'],
    	['nombre' => 'AE-09 Control I.' ,'url_plan_estudio' => 'documentos/4/AE-09 Control I.pdf'],
    	['nombre' => 'AE-10 Control I.' ,'url_plan_estudio' => 'documentos/4/AE-10 Control I.pdf'],
    	['nombre' => 'AE-20 Electromagnetismo.' ,'url_plan_estudio' => 'documentos/4/AE-20 Electromagnetismo.pdf'],
    	['nombre' => 'AE-38 Instrumentacion.' ,'url_plan_estudio' => 'documentos/4/AE-38 Instrumentacion.pdf'],
    	['nombre' => 'AE-40 Maquinas Electricas.' ,'url_plan_estudio' => 'documentos/4/AE-40 Maquinas Electricas.pdf'],
    	['nombre' => 'AE-42 Mecanica Clasica.' ,'url_plan_estudio' => 'documentos/4/AE-42 Mecanica Clasica.pdf'],
    	['nombre' => 'AE-51 Probabilidad y EstadÃ­stica.' ,'url_plan_estudio' => 'documentos/4/AE-51 Probabilidad y EstadÃ­stica.pdf'],
    	['nombre' => 'AE-58 Quimica.' ,'url_plan_estudio' => 'documentos/4/AE-58 Quimica.pdf'],
    	['nombre' => 'FA IELC-2010-211 Analisis Numerico.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Analisis Numerico.pdf'],
    	['nombre' => 'IELC Administracion Gerencial.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Administracion Gerencial.pdf'],
    	['nombre' => 'IELC Amplificadores Operacionales.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Amplificadores Operacionales.pdf'],
    	['nombre' => 'IELC Circuitos Electricos I.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Circuitos Electricos I.pdf'],
    	['nombre' => 'IELC Circuitos Electricos II.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Circuitos Electricos II.pdf'],
    	['nombre' => 'IELC Comunicacion Humana.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Comunicacion Humana.pdf'],
    	['nombre' => 'IELC Control Digital.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Control Digital.pdf'],
    	['nombre' => 'IELC Controladores Logicos Programables.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Controladores Logicos Programables.pdf'],
    	['nombre' => 'IELC Desarrollo Humano.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Desarrollo Humano.pdf'],
    	['nombre' => 'IELC Desarrollo Profesional.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Desarrollo Profesional.pdf'],
    	['nombre' => 'IELC Desarrollo y Evaluacion de Proyectos.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Desarrollo y Evaluacion de Proyectos.pdf'],
    	['nombre' => 'IELC Diodos y Transistores.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Diodos y Transistores.pdf'],
    	['nombre' => 'IELC DiseÃ±o con Transistores.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 DiseÃ±o con Transistores.pdf'],
    	['nombre' => 'IELC DiseÃ±o Digital.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 DiseÃ±o Digital.pdf'],
    	['nombre' => 'IELC DiseÃ±oo Digital con VHDL.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 DiseÃ±oo Digital con VHDL.pdf'],
    	['nombre' => 'IELC Electronica de Potencia.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Electronica de Potencia.pdf'],
    	['nombre' => 'IELC Fisica de Semicondutores.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Fisica de Semicondutores.pdf'],
    	['nombre' => 'IELC Fundamentos Financieros para la Toma de Decisiones.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Fundamentos Financieros para la Toma de Decisiones.pdf'],
    	['nombre' => 'IELC Introduccion a las Telecomunicaciones.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Introduccion a las Telecomunicaciones.pdf'],
    	['nombre' => 'IELC Marco Legal de la Empresa.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Marco Legal de la Empresa.pdf'],
    	['nombre' => 'IELC Mecanica Clasica.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Mecanica Clasica.pdf'],
    	['nombre' => 'IELC Mediciones Electricas.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Mediciones Electricas.pdf'],
    	['nombre' => 'IELC Microcontroladores.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Microcontroladores.pdf'],
    	['nombre' => 'IELC Optoelectronica.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Optoelectronica.pdf'],
    	['nombre' => 'IELC Programacion Estructurada.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Programacion Estructurada.pdf'],
    	['nombre' => 'IELC Programacion Visual.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Programacion Visual.pdf'],
    	['nombre' => 'IELC Teoria Electromagnetica.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Teoria Electromagnetica.pdf'],
    	['nombre' => 'IELC Topicos Selectos de Fisica.' ,'url_plan_estudio' => 'documentos/4/FA IELC-2010-211 Topicos Selectos de Fisica.pdf'],
    	['nombre' => 'IENR Admnistracion y Tecnicas de Conservacion.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Admnistracion y Tecnicas de Conservacion.pdf'],
    	['nombre' => 'IENR Auditoria Energetica.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Auditoria Energetica.pdf'],
    	['nombre' => 'IENR Biocombustibles.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Biocombustibles.pdf'],
    	['nombre' => 'IENR Bioquimica.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Bioquimica.pdf'],
    	['nombre' => 'IENR Circuitos Electricos I.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Circuitos Electricos I.pdf'],
    	['nombre' => 'IENR Circuitos Electricos II.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Circuitos Electricos II.pdf'],
    	['nombre' => 'IENR Comportamiento Humano en las Organizaciones.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Comportamiento Humano en las Organizaciones.pdf'],
    	['nombre' => 'IENR Dibujo.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Dibujo.pdf'],
    	['nombre' => 'IENR Energia Eolica.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Energia Eolica.pdf'],
    	['nombre' => 'IENR Estadistica y Diseño de Experimentos.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Estadistica y Diseño de Experimentos.pdf'],
    	['nombre' => 'IENR Estatica y Dinamica.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Estatica y Dinamica.pdf'],
    	['nombre' => 'IENR Formulacion y Evaluacion de Proyectos de Energias Renovables.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Formulacion y Evaluacion de Proyectos de Energias Renovables.pdf'],
    	['nombre' => 'IENR Fuentes Renovables de Energia.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Fuentes Renovables de Energia.pdf'],
    	['nombre' => 'IENR Gestion de Empresas de Energias Renovables.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Gestion de Empresas de Energias Renovables.pdf'],
    	['nombre' => 'IENR Instalaciones Electricas e Iluminacion.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Instalaciones Electricas e Iluminacion.pdf'],
    	['nombre' => 'IENR Maquinas Electricas.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Maquinas Electricas.pdf'],
    	['nombre' => 'IENR Maquinas Hidraulicas.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Maquinas Hidraulicas.pdf'],
    	['nombre' => 'IENR Marco Juridico en Gestion Energetica.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Marco Juridico en Gestion Energetica.pdf'],
    	['nombre' => 'IENR Mecanica de Fluidos.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Mecanica de Fluidos.pdf'],
    	['nombre' => 'IENR Metrologia Mecanica y Electrica.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Metrologia Mecanica y Electrica.pdf'],
    	['nombre' => 'IENR Microbiologia.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Microbiologia.pdf'],
    	['nombre' => 'IENR Optica y Semiconductores.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Optica y Semiconductores.pdf'],
    	['nombre' => 'IENR Programacion.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Programacion.pdf'],
    	['nombre' => 'IENR Quimica.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Quimica.pdf'],
    	['nombre' => 'IENR Refrigeracion y Aire Acondicionado.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Refrigeracion y Aire Acondicionado.pdf'],
    	['nombre' => 'IENR Resistencia de Materiales.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Resistencia de Materiales.pdf'],
    	['nombre' => 'IENR Simulacion de Sistemas de Energia Renovable.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Simulacion de Sistemas de Energia Renovable.pdf'],
    	['nombre' => 'IENR Sistemas Solares Fotovoltaicos y Termicos.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Sistemas Solares Fotovoltaicos y Termicos.pdf'],
    	['nombre' => 'IENR Sistemas Termicos.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Sistemas Termicos.pdf'],
    	['nombre' => 'IENR Talle de Sistemas de Informacion Geografica.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Talle de Sistemas de Informacion Geografica.pdf'],
    	['nombre' => 'IENR Tecnologia e Ingenieria de Materiales.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Tecnologia e Ingenieria de Materiales.pdf'],
    	['nombre' => 'IENR Termodinamica.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Termodinamica.pdf'],
    	['nombre' => 'IENR Transferencia de Calor.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/IENR-2010-217 Transferencia de Calor.pdf'],
    	['nombre' => 'Programas IENR-2010-217/~$mpetencias Especificas.' ,'url_plan_estudio' => 'documentos/5/Programas IENR-2010-217/~$mpetencias Especificas.doc'],
    	['nombre' => 'ACA-0907 TALLER DE ETICA.' ,'url_plan_estudio' => 'documentos/6/ACA-0907 TALLER DE ETICA.pdf'],
    	['nombre' => 'AE-15 DISEÑO ORGANIZACIONAL.' ,'url_plan_estudio' => 'documentos/6/AE-15 DISEÑO ORGANIZACIONAL.pdf'],
    	['nombre' => 'AE-35 GESTION ESTRATEGICA.' ,'url_plan_estudio' => 'documentos/6/AE-35 GESTION ESTRATEGICA.pdf'],
    	['nombre' => 'AE-45 MERCADOTECNIA ELECTRONICA.' ,'url_plan_estudio' => 'documentos/6/AE-45 MERCADOTECNIA ELECTRONICA.pdf'],
    	['nombre' => 'AE-69 CALIDAD APLICADA A LA GESTION EMPRESARIAL.' ,'url_plan_estudio' => 'documentos/6/AE-69 CALIDAD APLICADA A LA GESTION EMPRESARIAL.pdf'],
    	['nombre' => 'AE-72 EL EMPRENDEDOR Y LA INNOVACION.' ,'url_plan_estudio' => 'documentos/6/AE-72 EL EMPRENDEDOR Y LA INNOVACION.pdf'],
    	['nombre' => 'AEB-1082 SOFTWARE DE APLICACION EJECUTIVO.' ,'url_plan_estudio' => 'documentos/6/AEB-1082 SOFTWARE DE APLICACION EJECUTIVO.pdf'],
    	['nombre' => 'AEC-1014 DINAMICA SOCIAL.' ,'url_plan_estudio' => 'documentos/6/AEC-1014 DINAMICA SOCIAL.pdf'],
    	['nombre' => 'AEF-1071 ECONOMIA EMPRESARIAL.' ,'url_plan_estudio' => 'documentos/6/AEF-1071 ECONOMIA EMPRESARIAL.pdf'],
    	['nombre' => 'AEF-1073 FINANZAS EN LAS ORGANIZACIONES.' ,'url_plan_estudio' => 'documentos/6/AEF-1073 FINANZAS EN LAS ORGANIZACIONES.pdf'],
    	['nombre' => 'AEF-1074 FUNDAMENTOS DE GESTION EMPRESARIAL.' ,'url_plan_estudio' => 'documentos/6/AEF-1074 FUNDAMENTOS DE GESTION EMPRESARIAL.pdf'],
    	['nombre' => 'AEF-1075 GESTION DEL CAPITAL HUMANO.' ,'url_plan_estudio' => 'documentos/6/AEF-1075 GESTION DEL CAPITAL HUMANO.pdf'],
    	['nombre' => 'ALGEBRA LINEAL.' ,'url_plan_estudio' => 'documentos/6/ALGEBRA LINEAL.pdf'],
    	['nombre' => 'CALCULO DIFERENCIAL.' ,'url_plan_estudio' => 'documentos/6/CALCULO DIFERENCIAL.pdf'],
    	['nombre' => 'CALCULO INTEGRAL.' ,'url_plan_estudio' => 'documentos/6/CALCULO INTEGRAL.pdf'],
    	['nombre' => 'DESARROLLO SUSTENTABLE.' ,'url_plan_estudio' => 'documentos/6/DESARROLLO SUSTENTABLE.pdf'],
    	['nombre' => 'FUNDAMENTOS DE INVESTIGACION.' ,'url_plan_estudio' => 'documentos/6/FUNDAMENTOS DE INVESTIGACION.pdf'],
    	['nombre' => 'GEC-0926 MARCO LEGAL DE LAS ORGANIZACIONES.' ,'url_plan_estudio' => 'documentos/6/GEC-0926 MARCO LEGAL DE LAS ORGANIZACIONES.pdf'],
    	['nombre' => 'GEF-0924 (AEF 1076) INVESTIGACION DE OPERACIONES.' ,'url_plan_estudio' => 'documentos/6/GEF-0924 (AEF 1076) INVESTIGACION DE OPERACIONES.pdf'],
    	['nombre' => 'IGEM ADMINISTRACION DE LA SALUD Y SEGURIDAD OCUPACIONAL.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 ADMINISTRACION DE LA SALUD Y SEGURIDAD OCUPACIONAL.pdf'],
    	['nombre' => 'IGEM CADENA DE SUMINISTROS.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 CADENA DE SUMINISTROS.pdf'],
    	['nombre' => 'IGEM CONTABILIDAD ORIENTADA A LOS NEGOCIOS.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 CONTABILIDAD ORIENTADA A LOS NEGOCIOS.pdf'],
    	['nombre' => 'IGEM COSTOS EMPRESARIALES.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 COSTOS EMPRESARIALES.pdf'],
    	['nombre' => 'IGEM DESARROLLO HUMANO.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 DESARROLLO HUMANO.pdf'],
    	['nombre' => 'IGEM ENTORNO MACROECONOMICO.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 ENTORNO MACROECONOMICO.pdf'],
    	['nombre' => 'IGEM ESTADISTICA INFERENCIAL I.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 ESTADISTICA INFERENCIAL I.pdf'],
    	['nombre' => 'IGEM ESTADISTICA INFERENCIAL II.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 ESTADISTICA INFERENCIAL II.pdf'],
    	['nombre' => 'IGEM FUNDAMENTOS DE FISICA.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 FUNDAMENTOS DE FISICA.pdf'],
    	['nombre' => 'IGEM FUNDAMENTOS DE QUIMICA.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 FUNDAMENTOS DE QUIMICA.pdf'],
    	['nombre' => 'IGEM GESTION DE LA PRODUCCION I.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 GESTION DE LA PRODUCCION I.pdf'],
    	['nombre' => 'IGEM GESTION DE LA PRODUCCION II.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 GESTION DE LA PRODUCCION II.pdf'],
    	['nombre' => 'IGEM HABILIDADES DIRECTIVAS I.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 HABILIDADES DIRECTIVAS I.pdf'],
    	['nombre' => 'IGEM HABILIDADES DIRECTIVAS II.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 HABILIDADES DIRECTIVAS II.pdf'],
    	['nombre' => 'IGEM INGENIERIA DE PROCESOS.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 INGENIERIA DE PROCESOS.pdf'],
    	['nombre' => 'IGEM INGENIERIA ECONOMICA.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 INGENIERIA ECONOMICA.pdf'],
    	['nombre' => 'IGEM INSTRUMENTOS DE PRESUPUESTACION EMPRESARIAL.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 INSTRUMENTOS DE PRESUPUESTACION EMPRESARIAL.pdf'],
    	['nombre' => 'IGEM LEGISLACION LABORAL.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 LEGISLACION LABORAL.pdf'],
    	['nombre' => 'IGEM MERCADOTECNIA.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 MERCADOTECNIA.pdf'],
    	['nombre' => 'IGEM PLAN DE NEGOCIOS.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 PLAN DE NEGOCIOS.pdf'],
    	['nombre' => 'IGEM PROBABILIDAD Y ESTADISTICA DESCRIPTIVA.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 PROBABILIDAD Y ESTADISTICA DESCRIPTIVA.pdf'],
    	['nombre' => 'IGEM SISTEMAS DE INFORMACION DE MERCADOTECNIA.' ,'url_plan_estudio' => 'documentos/6/IGEM-2009-201 SISTEMAS DE INFORMACION DE MERCADOTECNIA.pdf'],
    	['nombre' => 'TALLER DE INVESTIGACION I.' ,'url_plan_estudio' => 'documentos/6/TALLER DE INVESTIGACION I.pdf'],
    	['nombre' => 'TALLER DE INVESTIGACION II.' ,'url_plan_estudio' => 'documentos/6/TALLER DE INVESTIGACION II.pdf'],
    	['nombre' => 'ADMINISTRACIÓN DE OPERACIONES I v2.' ,'url_plan_estudio' => 'documentos/7/ADMINISTRACIÓN DE OPERACIONES I v2.pdf'],
    	['nombre' => 'ADMINISTRACIÓN DE OPERACIONES II v2.' ,'url_plan_estudio' => 'documentos/7/ADMINISTRACIÓN DE OPERACIONES II v2.pdf'],
    	['nombre' => 'ADMINISTRACIÓN DE PROYECTOS v2.' ,'url_plan_estudio' => 'documentos/7/ADMINISTRACIÓN DE PROYECTOS v2.pdf'],
    	['nombre' => 'ADMINISTRACIÓN DEL MANTENIMIENTO V2.' ,'url_plan_estudio' => 'documentos/7/ADMINISTRACIÓN DEL MANTENIMIENTO V2.pdf'],
    	['nombre' => 'ALGORITMOS Y LENGUAJES DE PROGRAMACIÓN v2.' ,'url_plan_estudio' => 'documentos/7/ALGORITMOS Y LENGUAJES DE PROGRAMACIÓN v2.pdf'],
    	['nombre' => 'ANALISIS DE LA REALIDAD NACIONAL v2.' ,'url_plan_estudio' => 'documentos/7/ANALISIS DE LA REALIDAD NACIONAL v2.pdf'],
    	['nombre' => 'CONTROL ESTADISTICO DE LA CALIDA v2.' ,'url_plan_estudio' => 'documentos/7/CONTROL ESTADISTICO DE LA CALIDA v2.pdf'],
    	['nombre' => 'DIBUJO INDUSTRIAL v2.' ,'url_plan_estudio' => 'documentos/7/DIBUJO INDUSTRIAL v2.pdf'],
    	['nombre' => 'ELECTRICIDAD Y ELECTRONICA INDUSTRIAL v2.' ,'url_plan_estudio' => 'documentos/7/ELECTRICIDAD Y ELECTRONICA INDUSTRIAL v2.pdf'],
    	['nombre' => 'ERGONOMIA v2.' ,'url_plan_estudio' => 'documentos/7/ERGONOMIA v2.pdf'],
    	['nombre' => 'ESTUDIO DEL TRABAJO I v2.' ,'url_plan_estudio' => 'documentos/7/ESTUDIO DEL TRABAJO I v2.pdf'],
    	['nombre' => 'ESTUDIO DEL TRABAJO II v2.' ,'url_plan_estudio' => 'documentos/7/ESTUDIO DEL TRABAJO II v2.pdf'],
    	['nombre' => 'FISICA v2.' ,'url_plan_estudio' => 'documentos/7/FISICA v2.pdf'],
    	['nombre' => 'GESTION DE LOS SISTEMAS DE LOS SITEMAS DE CALIDAD v2.' ,'url_plan_estudio' => 'documentos/7/GESTION DE LOS SISTEMAS DE LOS SITEMAS DE CALIDAD v2.pdf'],
    	['nombre' => 'HIGIENE Y SEGURIDAD INDUSTRIAL .' ,'url_plan_estudio' => 'documentos/7/HIGIENE Y SEGURIDAD INDUSTRIAL .pdf'],
    	['nombre' => 'INGENIERIA DE SISTEMAS v2.' ,'url_plan_estudio' => 'documentos/7/INGENIERIA DE SISTEMAS v2.pdf'],
    	['nombre' => 'INVESTIGACION DE OPERACIONES I v2.' ,'url_plan_estudio' => 'documentos/7/INVESTIGACION DE OPERACIONES I v2.pdf'],
    	['nombre' => 'INVESTIGACION DE OPERACIONES II v2.' ,'url_plan_estudio' => 'documentos/7/INVESTIGACION DE OPERACIONES II v2.pdf'],
    	['nombre' => 'LOGISTICA y CADENA DE SUMINISTRO v2.' ,'url_plan_estudio' => 'documentos/7/LOGISTICA y CADENA DE SUMINISTRO v2.pdf'],
    	['nombre' => 'PLANEACION FINANCIERA v2.' ,'url_plan_estudio' => 'documentos/7/PLANEACION FINANCIERA v2.pdf'],
    	['nombre' => 'PLANEACION Y DISEÑO DE INSTALACIONES v2.' ,'url_plan_estudio' => 'documentos/7/PLANEACION Y DISEÑO DE INSTALACIONES v2.pdf'],
    	['nombre' => 'PROCESOS DE FABRICACIÓN v2.' ,'url_plan_estudio' => 'documentos/7/PROCESOS DE FABRICACIÓN v2.pdf'],
    	['nombre' => 'PROPIEDAD DE LOS MATERIALES v2.' ,'url_plan_estudio' => 'documentos/7/PROPIEDAD DE LOS MATERIALES v2.pdf'],
    	['nombre' => 'QUIMICA v2.' ,'url_plan_estudio' => 'documentos/7/QUIMICA v2.pdf'],
    	['nombre' => 'RELACIONES INDUSTRIALES v2.' ,'url_plan_estudio' => 'documentos/7/RELACIONES INDUSTRIALES v2.pdf'],
    	['nombre' => 'SIMULACIÓN v2.' ,'url_plan_estudio' => 'documentos/7/SIMULACIÓN v2.pdf'],
    	['nombre' => 'SISTEMAS DE MANUFACTURA.' ,'url_plan_estudio' => 'documentos/7/SISTEMAS DE MANUFACTURA.pdf'],
    	['nombre' => 'TALLER DE HERRAMIENTAS INTELECTUALES v2.' ,'url_plan_estudio' => 'documentos/7/TALLER DE HERRAMIENTAS INTELECTUALES v2.pdf'],
    	['nombre' => 'TALLER DE LIDERAZGO.' ,'url_plan_estudio' => 'documentos/7/TALLER DE LIDERAZGO.pdf'],
    	['nombre' => 'AC001 Calculo Diferencial.' ,'url_plan_estudio' => 'documentos/8/AC001 Calculo Diferencial.pdf'],
    	['nombre' => 'AC002 Calculo Integral.' ,'url_plan_estudio' => 'documentos/8/AC002 Calculo Integral.pdf'],
    	['nombre' => 'AC003 Algebra Lineal.' ,'url_plan_estudio' => 'documentos/8/AC003 Algebra Lineal.pdf'],
    	['nombre' => 'AC004 Calculo Vectorial.' ,'url_plan_estudio' => 'documentos/8/AC004 Calculo Vectorial.pdf'],
    	['nombre' => 'AC005 Ecuaciones Diferenciales.' ,'url_plan_estudio' => 'documentos/8/AC005 Ecuaciones Diferenciales.pdf'],
    	['nombre' => 'AC006 Fundamentos de Investigacion.' ,'url_plan_estudio' => 'documentos/8/AC006 Fundamentos de Investigacion.pdf'],
    	['nombre' => 'AC007 Taller de Etica.' ,'url_plan_estudio' => 'documentos/8/AC007 Taller de Etica.pdf'],
    	['nombre' => 'AC008 Desarrollo Sustentable.' ,'url_plan_estudio' => 'documentos/8/AC008 Desarrollo Sustentable.pdf'],
    	['nombre' => 'AC009 Taller de Investigacion I.' ,'url_plan_estudio' => 'documentos/8/AC009 Taller de Investigacion I.pdf'],
    	['nombre' => 'AC010 Taller de Investigacion II.' ,'url_plan_estudio' => 'documentos/8/AC010 Taller de Investigacion II.pdf'],
    	['nombre' => 'AE020 Electromagnetismo.' ,'url_plan_estudio' => 'documentos/8/AE020 Electromagnetismo.pdf'],
    	['nombre' => 'AE043 Mecanismos.' ,'url_plan_estudio' => 'documentos/8/AE043 Mecanismos.pdf'],
    	['nombre' => 'AE046 Metodos Numericos.' ,'url_plan_estudio' => 'documentos/8/AE046 Metodos Numericos.pdf'],
    	['nombre' => 'AE067 Vibraciones Mecanicas.' ,'url_plan_estudio' => 'documentos/8/AE067 Vibraciones Mecanicas.pdf'],
    	['nombre' => 'AE091 Dinamica.' ,'url_plan_estudio' => 'documentos/8/AE091 Dinamica.pdf'],
    	['nombre' => 'AE093 Metrologia y Normalizacion.' ,'url_plan_estudio' => 'documentos/8/AE093 Metrologia y Normalizacion.pdf'],
    	['nombre' => 'Algoritmos y Programacion.' ,'url_plan_estudio' => 'documentos/8/Algoritmos y Programacion.pdf'],
    	['nombre' => 'Automatización Industrial.' ,'url_plan_estudio' => 'documentos/8/Automatización Industrial.pdf'],
    	['nombre' => 'Calidad.' ,'url_plan_estudio' => 'documentos/8/Calidad.pdf'],
    	['nombre' => 'Circuitos y Máquinas Eléctricas.' ,'url_plan_estudio' => 'documentos/8/Circuitos y Máquinas Eléctricas.pdf'],
    	['nombre' => 'Contabilidad y costos.' ,'url_plan_estudio' => 'documentos/8/Contabilidad y costos.pdf'],
    	['nombre' => 'Dibujo Mecánico.' ,'url_plan_estudio' => 'documentos/8/Dibujo Mecánico.pdf'],
    	['nombre' => 'Diseño Mecanico I.' ,'url_plan_estudio' => 'documentos/8/Diseño Mecanico I.pdf'],
    	['nombre' => 'Diseño Mecanico II.' ,'url_plan_estudio' => 'documentos/8/Diseño Mecanico II.pdf'],
    	['nombre' => 'Estatica.' ,'url_plan_estudio' => 'documentos/8/Estatica.pdf'],
    	['nombre' => 'Gestion de Proyectos.' ,'url_plan_estudio' => 'documentos/8/Gestion de Proyectos.pdf'],
    	['nombre' => 'Higiene y Seguridad Industrial.' ,'url_plan_estudio' => 'documentos/8/Higiene y Seguridad Industrial.pdf'],
    	['nombre' => 'Ingenieria de Materiales No metalicos.' ,'url_plan_estudio' => 'documentos/8/Ingenieria de Materiales No metalicos.pdf'],
    	['nombre' => 'Ingeniería de Materiales Metálicos.' ,'url_plan_estudio' => 'documentos/8/Ingeniería de Materiales Metálicos.pdf'],
    	['nombre' => 'Instrumentación y Control.' ,'url_plan_estudio' => 'documentos/8/Instrumentación y Control.pdf'],
    	['nombre' => 'Mantenimiento.' ,'url_plan_estudio' => 'documentos/8/Mantenimiento.pdf'],
    	['nombre' => 'Mecanica de Fluidos.' ,'url_plan_estudio' => 'documentos/8/Mecanica de Fluidos.pdf'],
    	['nombre' => 'Mecánica de Materiales I.' ,'url_plan_estudio' => 'documentos/8/Mecánica de Materiales I.pdf'],
    	['nombre' => 'Mecánica de Materiales II.' ,'url_plan_estudio' => 'documentos/8/Mecánica de Materiales II.pdf'],
    	['nombre' => 'Máquinas de Fluidos Comprensibles.' ,'url_plan_estudio' => 'documentos/8/Máquinas de Fluidos Comprensibles.pdf'],
    	['nombre' => 'Máquinas de Fluidos Incompresibles.' ,'url_plan_estudio' => 'documentos/8/Máquinas de Fluidos Incompresibles.pdf'],
    	['nombre' => 'Probabilidad y Estadistica.' ,'url_plan_estudio' => 'documentos/8/Probabilidad y Estadistica.pdf'],
    	['nombre' => 'Proceso Administrativo.' ,'url_plan_estudio' => 'documentos/8/Proceso Administrativo.pdf'],
    	['nombre' => 'Procesos de Manufactura.' ,'url_plan_estudio' => 'documentos/8/Procesos de Manufactura.pdf'],
    	['nombre' => 'Quimica.' ,'url_plan_estudio' => 'documentos/8/Quimica.pdf'],
    	['nombre' => 'Refrigeración y Aire Acondicionado .' ,'url_plan_estudio' => 'documentos/8/Refrigeración y Aire Acondicionado .pdf'],
    	['nombre' => 'Sistemas de Generacion de Energia.' ,'url_plan_estudio' => 'documentos/8/Sistemas de Generacion de Energia.pdf'],
    	['nombre' => 'Sistemas e Instalaciones Hidráulicas.' ,'url_plan_estudio' => 'documentos/8/Sistemas e Instalaciones Hidráulicas.pdf'],
    	['nombre' => 'Sistemas Electrónicos.' ,'url_plan_estudio' => 'documentos/8/Sistemas Electrónicos.pdf'],
    	['nombre' => 'Termodinámica.' ,'url_plan_estudio' => 'documentos/8/Termodinámica.pdf'],
    	['nombre' => 'Transferencia de Calor.' ,'url_plan_estudio' => 'documentos/8/Transferencia de Calor.pdf'],
    	['nombre' => 'AC001 Calculo Diferencial.' ,'url_plan_estudio' => 'documentos/9/AC001 Calculo Diferencial.pdf'],
    	['nombre' => 'AC002 Calculo Integral.' ,'url_plan_estudio' => 'documentos/9/AC002 Calculo Integral.pdf'],
    	['nombre' => 'AC003 Algebra Lineal.' ,'url_plan_estudio' => 'documentos/9/AC003 Algebra Lineal.pdf'],
    	['nombre' => 'AC004 Calculo Vectorial.' ,'url_plan_estudio' => 'documentos/9/AC004 Calculo Vectorial.pdf'],
    	['nombre' => 'AC005 Ecuaciones Diferenciales.' ,'url_plan_estudio' => 'documentos/9/AC005 Ecuaciones Diferenciales.pdf'],
    	['nombre' => 'AC006 Fundamentos de Investigacion.' ,'url_plan_estudio' => 'documentos/9/AC006 Fundamentos de Investigacion.pdf'],
    	['nombre' => 'AC007 Taller de Etica.' ,'url_plan_estudio' => 'documentos/9/AC007 Taller de Etica.pdf'],
    	['nombre' => 'AC008 Desarrollo Sustentable.' ,'url_plan_estudio' => 'documentos/9/AC008 Desarrollo Sustentable.pdf'],
    	['nombre' => 'AC009 Taller de Investigacion I.' ,'url_plan_estudio' => 'documentos/9/AC009 Taller de Investigacion I.pdf'],
    	['nombre' => 'AC010 Taller de Investigacion II.' ,'url_plan_estudio' => 'documentos/9/AC010 Taller de Investigacion II.pdf'],
    	['nombre' => 'Administración y Contabilidad.' ,'url_plan_estudio' => 'documentos/9/Administración y Contabilidad.pdf'],
    	['nombre' => 'AE013 Dibujo Asistido por Computadora.' ,'url_plan_estudio' => 'documentos/9/AE013 Dibujo Asistido por Computadora.pdf'],
    	['nombre' => 'AE020 Electromagnetismo.' ,'url_plan_estudio' => 'documentos/9/AE020 Electromagnetismo.pdf'],
    	['nombre' => 'AE038 Instrumentacion.' ,'url_plan_estudio' => 'documentos/9/AE038 Instrumentacion.pdf'],
    	['nombre' => 'AE040 Maquinas Electricas.' ,'url_plan_estudio' => 'documentos/9/AE040 Maquinas Electricas.pdf'],
    	['nombre' => 'AE043 Mecanismos.' ,'url_plan_estudio' => 'documentos/9/AE043 Mecanismos.pdf'],
    	['nombre' => 'AE046 Metodos Numericos.' ,'url_plan_estudio' => 'documentos/9/AE046 Metodos Numericos.pdf'],
    	['nombre' => 'AE047 Metrologia y Normalizacion.' ,'url_plan_estudio' => 'documentos/9/AE047 Metrologia y Normalizacion.pdf'],
    	['nombre' => 'AE058 Quimica.' ,'url_plan_estudio' => 'documentos/9/AE058 Quimica.pdf'],
    	['nombre' => 'AE067 Vibraciones Mecanicas.' ,'url_plan_estudio' => 'documentos/9/AE067 Vibraciones Mecanicas.pdf'],
    	['nombre' => 'Análisis de Circuitos Eléctricos.' ,'url_plan_estudio' => 'documentos/9/Análisis de Circuitos Eléctricos.pdf'],
    	['nombre' => 'Análisis de Fluidos.' ,'url_plan_estudio' => 'documentos/9/Análisis de Fluidos.pdf'],
    	['nombre' => 'Ciencia e Ingeniería de los Materiales.' ,'url_plan_estudio' => 'documentos/9/Ciencia e Ingeniería de los Materiales.pdf'],
    	['nombre' => 'Circuitos Hidráulicos y Neumáticos.' ,'url_plan_estudio' => 'documentos/9/Circuitos Hidráulicos y Neumáticos.pdf'],
    	['nombre' => 'Control.' ,'url_plan_estudio' => 'documentos/9/Control.pdf'],
    	['nombre' => 'Controladores Lógicos Programables.' ,'url_plan_estudio' => 'documentos/9/Controladores Lógicos Programables.pdf'],
    	['nombre' => 'Dinámica de Sistemas.' ,'url_plan_estudio' => 'documentos/9/Dinámica de Sistemas.pdf'],
    	['nombre' => 'Dinámica.' ,'url_plan_estudio' => 'documentos/9/Dinámica.pdf'],
    	['nombre' => 'Diseño de Elementos Mecánicos.' ,'url_plan_estudio' => 'documentos/9/Diseño de Elementos Mecánicos.pdf'],
    	['nombre' => 'Electrónica Analógica.' ,'url_plan_estudio' => 'documentos/9/Electrónica Analógica.pdf'],
    	['nombre' => 'Electrónica de Potencia Aplicada.' ,'url_plan_estudio' => 'documentos/9/Electrónica de Potencia Aplicada.pdf'],
    	['nombre' => 'Electrónica Digital.' ,'url_plan_estudio' => 'documentos/9/Electrónica Digital.pdf'],
    	['nombre' => 'Estadistica y Control de Calidad.' ,'url_plan_estudio' => 'documentos/9/Estadistica y Control de Calidad.pdf'],
    	['nombre' => 'Estática.' ,'url_plan_estudio' => 'documentos/9/Estática.pdf'],
    	['nombre' => 'Formulación y Evaluación de Proyectos.' ,'url_plan_estudio' => 'documentos/9/Formulación y Evaluación de Proyectos.pdf'],
    	['nombre' => 'Fundamentos de termodinámica.' ,'url_plan_estudio' => 'documentos/9/Fundamentos de termodinámica.pdf'],
    	['nombre' => 'Mantenimiento.' ,'url_plan_estudio' => 'documentos/9/Mantenimiento.pdf'],
    	['nombre' => 'Manufactura Avanzada.' ,'url_plan_estudio' => 'documentos/9/Manufactura Avanzada.pdf'],
    	['nombre' => 'Mecánica de Materiales.' ,'url_plan_estudio' => 'documentos/9/Mecánica de Materiales.pdf'],
    	['nombre' => 'Microcontroladores.' ,'url_plan_estudio' => 'documentos/9/Microcontroladores.pdf'],
    	['nombre' => 'Procesos de fabricación.' ,'url_plan_estudio' => 'documentos/9/Procesos de fabricación.pdf'],
    	['nombre' => 'Programación Avanzada.' ,'url_plan_estudio' => 'documentos/9/Programación Avanzada.pdf'],
    	['nombre' => 'Programación Básica.' ,'url_plan_estudio' => 'documentos/9/Programación Básica.pdf'],
    	['nombre' => 'Robótica.' ,'url_plan_estudio' => 'documentos/9/Robótica.pdf'],
    	['nombre' => 'AC001 Calculo Diferencial.' ,'url_plan_estudio' => 'documentos/10/AC001 Calculo Diferencial.pdf'],
    	['nombre' => 'AC002 Calculo Integral.' ,'url_plan_estudio' => 'documentos/10/AC002 Calculo Integral.pdf'],
    	['nombre' => 'AC003 Algebra Lineal.' ,'url_plan_estudio' => 'documentos/10/AC003 Algebra Lineal.pdf'],
    	['nombre' => 'AC004 Calculo Vectorial.' ,'url_plan_estudio' => 'documentos/10/AC004 Calculo Vectorial.pdf'],
    	['nombre' => 'AC005 Ecuaciones Diferenciales.' ,'url_plan_estudio' => 'documentos/10/AC005 Ecuaciones Diferenciales.pdf'],
    	['nombre' => 'AC006 Fundamentos de Investigacion.' ,'url_plan_estudio' => 'documentos/10/AC006 Fundamentos de Investigacion.pdf'],
    	['nombre' => 'AC007 Taller de Etica.' ,'url_plan_estudio' => 'documentos/10/AC007 Taller de Etica.pdf'],
    	['nombre' => 'AC008 Desarrollo Sustentable.' ,'url_plan_estudio' => 'documentos/10/AC008 Desarrollo Sustentable.pdf'],
    	['nombre' => 'AC009 Taller de Investigacion I.' ,'url_plan_estudio' => 'documentos/10/AC009 Taller de Investigacion I.pdf'],
    	['nombre' => 'AC010 Taller de Investigacion II.' ,'url_plan_estudio' => 'documentos/10/AC010 Taller de Investigacion II.pdf'],
    	['nombre' => 'Administración de Base de Datos.' ,'url_plan_estudio' => 'documentos/10/Administración de Base de Datos.pdf'],
    	['nombre' => 'Administración de redes..' ,'url_plan_estudio' => 'documentos/10/Administración de redes..pdf'],
    	['nombre' => 'AE008 Contabilidad Financiera.' ,'url_plan_estudio' => 'documentos/10/AE008 Contabilidad Financiera.pdf'],
    	['nombre' => 'AE026 Estructura de Datos.' ,'url_plan_estudio' => 'documentos/10/AE026 Estructura de Datos.pdf'],
    	['nombre' => 'AE031 Fundamentos de Base de Datos.' ,'url_plan_estudio' => 'documentos/10/AE031 Fundamentos de Base de Datos.pdf'],
    	['nombre' => 'AE034 Fundamentos de Telecomunicaciones.' ,'url_plan_estudio' => 'documentos/10/AE034 Fundamentos de Telecomunicaciones.pdf'],
    	['nombre' => 'AE041 Matematicas Discretas.' ,'url_plan_estudio' => 'documentos/10/AE041 Matematicas Discretas.pdf'],
    	['nombre' => 'AE052 Probabilidad y Estadistica.' ,'url_plan_estudio' => 'documentos/10/AE052 Probabilidad y Estadistica.pdf'],
    	['nombre' => 'AE055 Programacion Web.' ,'url_plan_estudio' => 'documentos/10/AE055 Programacion Web.pdf'],
    	['nombre' => 'AE058 Quimica.' ,'url_plan_estudio' => 'documentos/10/AE058 Quimica.pdf'],
    	['nombre' => 'AE061 Sistemas Operativos I.' ,'url_plan_estudio' => 'documentos/10/AE061 Sistemas Operativos I.pdf'],
    	['nombre' => 'AE085 Fundamentos de Programacion.' ,'url_plan_estudio' => 'documentos/10/AE085 Fundamentos de Programacion.pdf'],
    	['nombre' => 'AE086 Programacion Orientada a Objetos.' ,'url_plan_estudio' => 'documentos/10/AE086 Programacion Orientada a Objetos.pdf'],
    	['nombre' => 'Arquitectura de Computadoras..' ,'url_plan_estudio' => 'documentos/10/Arquitectura de Computadoras..pdf'],
    	['nombre' => 'Conmutación y Enrutamiento en Redes de Datos.' ,'url_plan_estudio' => 'documentos/10/Conmutación y Enrutamiento en Redes de Datos.pdf'],
    	['nombre' => 'Cultura Empresarial.' ,'url_plan_estudio' => 'documentos/10/Cultura Empresarial.pdf'],
    	['nombre' => 'Especialidades/RETICULA ISC 2015 ESPECIALIDAD.' ,'url_plan_estudio' => 'documentos/10/Especialidades/RETICULA ISC 2015 ESPECIALIDAD.pdf'],
    	['nombre' => 'Especialidades/Retícula de la Especialidad de Ingeniería de Software-2012.' ,'url_plan_estudio' => 'documentos/10/Especialidades/Retícula de la Especialidad de Ingeniería de Software-2012.pdf'],
    	['nombre' => 'Fundamentos de Ingeniería de Software.' ,'url_plan_estudio' => 'documentos/10/Fundamentos de Ingeniería de Software.pdf'],
    	['nombre' => 'Física General.' ,'url_plan_estudio' => 'documentos/10/Física General.pdf'],
    	['nombre' => 'Gestión de Proyectos de Software.' ,'url_plan_estudio' => 'documentos/10/Gestión de Proyectos de Software.pdf'],
    	['nombre' => 'Graficación.' ,'url_plan_estudio' => 'documentos/10/Graficación.pdf'],
    	['nombre' => 'Ingeniería de Software.' ,'url_plan_estudio' => 'documentos/10/Ingeniería de Software.pdf'],
    	['nombre' => 'Inteligencia Artificial..' ,'url_plan_estudio' => 'documentos/10/Inteligencia Artificial..pdf'],
    	['nombre' => 'Investigación de operaciones.' ,'url_plan_estudio' => 'documentos/10/Investigación de operaciones.pdf'],
    	['nombre' => 'Lenguajes de Interfaz.' ,'url_plan_estudio' => 'documentos/10/Lenguajes de Interfaz.pdf'],
    	['nombre' => 'Lenguajes y Autómatas I.' ,'url_plan_estudio' => 'documentos/10/Lenguajes y Autómatas I.pdf'],
    	['nombre' => 'Lenguajes y Autómatas II..' ,'url_plan_estudio' => 'documentos/10/Lenguajes y Autómatas II..pdf'],
    	['nombre' => 'Métodos numéricos.' ,'url_plan_estudio' => 'documentos/10/Métodos numéricos.pdf'],
    	['nombre' => 'Principios Eléctricos y Aplicaciones Digitales.' ,'url_plan_estudio' => 'documentos/10/Principios Eléctricos y Aplicaciones Digitales.pdf'],
    	['nombre' => 'Programación Lógica y Funcional..' ,'url_plan_estudio' => 'documentos/10/Programación Lógica y Funcional..pdf'],
    	['nombre' => 'Redes de Computadoras.' ,'url_plan_estudio' => 'documentos/10/Redes de Computadoras.pdf'],
    	['nombre' => 'Simulación.' ,'url_plan_estudio' => 'documentos/10/Simulación.pdf'],
    	['nombre' => 'Sistemas Programables.' ,'url_plan_estudio' => 'documentos/10/Sistemas Programables.pdf'],
    	['nombre' => 'Taller de Administración.' ,'url_plan_estudio' => 'documentos/10/Taller de Administración.pdf'],
    	['nombre' => 'Taller de base de datos.' ,'url_plan_estudio' => 'documentos/10/Taller de base de datos.pdf'],
    	['nombre' => 'Taller de Sistemas Operativos.' ,'url_plan_estudio' => 'documentos/10/Taller de Sistemas Operativos.pdf'],
    	['nombre' => 'Tópicos Avanzados de Programación..' ,'url_plan_estudio' => 'documentos/10/Tópicos Avanzados de Programación..pdf'],
    	['nombre' => 'AC001 Calculo Diferencial.' ,'url_plan_estudio' => 'documentos/11/AC001 Calculo Diferencial.pdf'],
    	['nombre' => 'AC002 Calculo Integral.' ,'url_plan_estudio' => 'documentos/11/AC002 Calculo Integral.pdf'],
    	['nombre' => 'AC003 Algebra Lineal.' ,'url_plan_estudio' => 'documentos/11/AC003 Algebra Lineal.pdf'],
    	['nombre' => 'AC004 Calculo Vectorial.' ,'url_plan_estudio' => 'documentos/11/AC004 Calculo Vectorial.pdf'],
    	['nombre' => 'AC005 Ecuaciones Diferenciales.' ,'url_plan_estudio' => 'documentos/11/AC005 Ecuaciones Diferenciales.pdf'],
    	['nombre' => 'AC006 Fundamentos de Investigacion.' ,'url_plan_estudio' => 'documentos/11/AC006 Fundamentos de Investigacion.pdf'],
    	['nombre' => 'AC007 Taller de Etica.' ,'url_plan_estudio' => 'documentos/11/AC007 Taller de Etica.pdf'],
    	['nombre' => 'AC008 Desarrollo Sustentable.' ,'url_plan_estudio' => 'documentos/11/AC008 Desarrollo Sustentable.pdf'],
    	['nombre' => 'AC009 Taller de Investigacion I.' ,'url_plan_estudio' => 'documentos/11/AC009 Taller de Investigacion I.pdf'],
    	['nombre' => 'AC010 Taller de Investigacion II.' ,'url_plan_estudio' => 'documentos/11/AC010 Taller de Investigacion II.pdf'],
    	['nombre' => 'Administración de Proyectos.' ,'url_plan_estudio' => 'documentos/11/Administración de Proyectos.pdf'],
    	['nombre' => 'Administración Gerencial.' ,'url_plan_estudio' => 'documentos/11/Administración Gerencial.pdf'],
    	['nombre' => 'Administración y Seguridad de Redes.' ,'url_plan_estudio' => 'documentos/11/Administración y Seguridad de Redes.pdf'],
    	['nombre' => 'AE011 Desarrollo Aplicaciones Dispositivos Moviles.' ,'url_plan_estudio' => 'documentos/11/AE011 Desarrollo Aplicaciones Dispositivos Moviles.pdf'],
    	['nombre' => 'AE031 Fundamentos de Base de Datos.' ,'url_plan_estudio' => 'documentos/11/AE031 Fundamentos de Base de Datos.pdf'],
    	['nombre' => 'AE032 Fundamentos de Programacion.' ,'url_plan_estudio' => 'documentos/11/AE032 Fundamentos de Programacion.pdf'],
    	['nombre' => 'AE052 Probabilidad y Estadistica.' ,'url_plan_estudio' => 'documentos/11/AE052 Probabilidad y Estadistica.pdf'],
    	['nombre' => 'AE054 Programacion Orientada a Objetos.' ,'url_plan_estudio' => 'documentos/11/AE054 Programacion Orientada a Objetos.pdf'],
    	['nombre' => 'AE055 Programacion Web.' ,'url_plan_estudio' => 'documentos/11/AE055 Programacion Web.pdf'],
    	['nombre' => 'AE061 Sistemas Operativos I.' ,'url_plan_estudio' => 'documentos/11/AE061 Sistemas Operativos I.pdf'],
    	['nombre' => 'AE062 Sistemas Operativos II.' ,'url_plan_estudio' => 'documentos/11/AE062 Sistemas Operativos II.pdf'],
    	['nombre' => 'AE063 Taller de Base de Datos.' ,'url_plan_estudio' => 'documentos/11/AE063 Taller de Base de Datos.pdf'],
    	['nombre' => 'Análisis de Señales y Sistemas de Comunicación.' ,'url_plan_estudio' => 'documentos/11/Análisis de Señales y Sistemas de Comunicación.pdf'],
    	['nombre' => 'Arquitectura de Computadoras.' ,'url_plan_estudio' => 'documentos/11/Arquitectura de Computadoras.pdf'],
    	['nombre' => 'Auditoría en Tecnologías de la Información.' ,'url_plan_estudio' => 'documentos/11/Auditoría en Tecnologías de la Información.pdf'],
    	['nombre' => 'Bases de Datos Distribuidas.' ,'url_plan_estudio' => 'documentos/11/Bases de Datos Distribuidas.pdf'],
    	['nombre' => 'Circuitos Eléctricos y Electrónicos.' ,'url_plan_estudio' => 'documentos/11/Circuitos Eléctricos y Electrónicos.pdf'],
    	['nombre' => 'Contabilidad y Costos.' ,'url_plan_estudio' => 'documentos/11/Contabilidad y Costos.pdf'],
    	['nombre' => 'Desarrollo de Emprendedores.' ,'url_plan_estudio' => 'documentos/11/Desarrollo de Emprendedores.pdf'],
    	['nombre' => 'Electricidad y Magnetismo.' ,'url_plan_estudio' => 'documentos/11/Electricidad y Magnetismo.pdf'],
    	['nombre' => 'Especialidades/RETICULA ESPECIALIDAD EN TICS-2016.' ,'url_plan_estudio' => 'documentos/11/Especialidades/RETICULA ESPECIALIDAD EN TICS-2016.pdf'],
    	['nombre' => 'Especialidades/RETICULA tic 2012 ESPECIALIDAD.' ,'url_plan_estudio' => 'documentos/11/Especialidades/RETICULA tic 2012 ESPECIALIDAD.pdf'],
    	['nombre' => 'Estructuras y Organización de Datos.' ,'url_plan_estudio' => 'documentos/11/Estructuras y Organización de Datos.pdf'],
    	['nombre' => 'Fundamentos de Redes.' ,'url_plan_estudio' => 'documentos/11/Fundamentos de Redes.pdf'],
    	['nombre' => 'Ingeniería de Software.' ,'url_plan_estudio' => 'documentos/11/Ingeniería de Software.pdf'],
    	['nombre' => 'Ingeniería del Conocimiento.' ,'url_plan_estudio' => 'documentos/11/Ingeniería del Conocimiento.pdf'],
    	['nombre' => 'Interacción Humano Computadora.' ,'url_plan_estudio' => 'documentos/11/Interacción Humano Computadora.pdf'],
    	['nombre' => 'Introduccion a las TICs.' ,'url_plan_estudio' => 'documentos/11/Introduccion a las TICs.pdf'],
    	['nombre' => 'Matematicas Discretas I.' ,'url_plan_estudio' => 'documentos/11/Matematicas Discretas I.pdf'],
    	['nombre' => 'Matematicas Discretas II.' ,'url_plan_estudio' => 'documentos/11/Matematicas Discretas II.pdf'],
    	['nombre' => 'Matematicas para la Toma de Decisiones.' ,'url_plan_estudio' => 'documentos/11/Matematicas para la Toma de Decisiones.pdf'],
    	['nombre' => 'Matemáticas Aplicadas a Comunicaciones.' ,'url_plan_estudio' => 'documentos/11/Matemáticas Aplicadas a Comunicaciones.pdf'],
    	['nombre' => 'Negocios Electrónicos I.' ,'url_plan_estudio' => 'documentos/11/Negocios Electrónicos I.pdf'],
    	['nombre' => 'Negocios Electrónicos II.' ,'url_plan_estudio' => 'documentos/11/Negocios Electrónicos II.pdf'],
    	['nombre' => 'Programación II.' ,'url_plan_estudio' => 'documentos/11/Programación II.pdf'],
    	['nombre' => 'Redes de Computadoras.' ,'url_plan_estudio' => 'documentos/11/Redes de Computadoras.pdf'],
    	['nombre' => 'Redes Emergentes.' ,'url_plan_estudio' => 'documentos/11/Redes Emergentes.pdf'],
    	['nombre' => 'Taller de Ingeniería de Software.' ,'url_plan_estudio' => 'documentos/11/Taller de Ingeniería de Software.pdf'],
    	['nombre' => 'Tecnologías Inalámbricas.' ,'url_plan_estudio' => 'documentos/11/Tecnologías Inalámbricas.pdf'],
    	['nombre' => 'Telecomunicaciones.' ,'url_plan_estudio' => 'documentos/11/Telecomunicaciones.pdf'],
    	];
    	foreach ($materias as $value) {
    		\App\Materia::create($value);
    	}
    }
}
